### ISSUE TITLE
Issues in the User manual

### ISSUE THREAD

**Issue by EmilienChinsy** [algosup/2024-2025-project-1-fpga-team-4#18]
You need to remove any mention of the river and of the five homes as we have none of these

You write this in the table of contents:
Platform: State the operating systems or devices the game can be played on
can you fix all similar issues in the table of contents please

For the installation, Clementine has made bash files, see with her if it's a good idea to write everything or not.

For the levels, only the speed of the cars will increase.
When the frog gets hit, the score is reset to 0

In common issues, when you talk about the game crashing it's not a common issue, I don't think it has ever happened.

**Comment by Ianlaur** [comment]
Hi Emilien, just corrected all of what you requested. I'll push the document please feel free to let me know if there are any other issues that you've spotted.
